version: 2
jobs:
  j-build:        
    working_directory: ~/gintelandr
    environment:      
      _JAVA_OPTIONS: "-Xmx3g -Djdk.module.illegalAccess=deny"
      _JAVAC_OPTIONS: "-Xlint:unchecked -Xlint:deprecation"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps: 
      - checkout       
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: ensure gradlew is executable...
          command: chmod +x ./gradlew
      - run: mkdir -p /tmp/artifacts
      - run:
          name: Build
          command: |            
            ~/gintelandr/gradlew build -x test
            mkdir -p /tmp/gintelandr
            unzip ~/gintelandr/build/distributions/gintelandr.zip -d /tmp
            chmod +x /tmp/gintelandr/bin/gintelandr
            GINTELANDR_CONSOLE=/tmp/gintelandr/bin/gintelandr
            VERSION=$($GINTELANDR_CONSOLE --version)
            cp ~/gintelandr/build/distributions/gintelandr.tar /tmp/artifacts/gintelandr-$VERSION.tar
            cp ~/gintelandr/build/distributions/gintelandr.zip /tmp/artifacts/gintelandr-$VERSION.zip
            cp ~/gintelandr/README.md /tmp/artifacts
            cp ~/gintelandr/HISTORY.md /tmp/artifacts
            echo $VERSION > /tmp/artifacts/ver.txt
      - store_artifacts:
          path: /tmp/artifacts
          destination: ./        
      - persist_to_workspace:
          root: /tmp/artifacts          
          paths:            
            - ./*
  j-test:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout       
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: ensure gradlew is executable...
          command: chmod +x ./gradlew
      - run: mkdir -p /tmp/artifacts
      - run:
          name: Test
          command: |
            ~/gintelandr/gradlew build
            VERSION=`cat /tmp/artifacts/ver.txt`
            tar cvzf ~/gintelandr/gintelandr-test-results-$VERSION.tar.gz ~/gintelandr/build/reports/*
            zip -r ~/gintelandr/gintelandr-test-results-$VERSION.zip ~/gintelandr/build/reports/*
      - store_artifacts:
          path: /tmp/artifacts
          destination: ./
      - persist_to_workspace:
          root: /tmp/artifacts          
          paths:            
            - ./*
  j-deploy:
    docker:
      - image: circleci/golang:1.12      
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: Deploy
          command: |            
            go get github.com/tcnksm/ghr
            VERSION=`cat /tmp/artifacts/ver.txt`
            rm /tmp/artifacts/ver.txt
            echo ${GITHUB_TOKEN}
            echo ${CIRCLE_PROJECT_USERNAME}
            echo ${CIRCLE_PROJECT_REPONAME}
            echo ${CIRCLE_SHA1}
            echo ${VERSION}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts
          destination: ./
workflows:
  version: 2
  wf-build-test:
    jobs:
      - j-build
      - j-test:
          requires:
            - j-build
  wf-build-test-deploy:
    jobs:
      - j-build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(?<=^[Vv]|^)(?:(?<major>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<minor>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<patch>(?:0|[1-9](?:(?:0|[1-9])+)*))(?:-(?<prerelease>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*)))*))?(?:[+](?<build>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+)))*))?)$/
      - j-test:
          requires:
            - j-build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(?<=^[Vv]|^)(?:(?<major>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<minor>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<patch>(?:0|[1-9](?:(?:0|[1-9])+)*))(?:-(?<prerelease>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*)))*))?(?:[+](?<build>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+)))*))?)$/
      - j-deploy:
          requires:
            - j-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(?<=^[Vv]|^)(?:(?<major>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<minor>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<patch>(?:0|[1-9](?:(?:0|[1-9])+)*))(?:-(?<prerelease>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*)))*))?(?:[+](?<build>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+)))*))?)$/
