/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bw.mitp0sh.gintelandr;

import org.junit.Test;
import static org.junit.Assert.*;

public class GintelandrConsoleTest {
    @Test public void testGintelandrConsole() {    	
        assertTrue("blah 'true'", true);
    }
}
